/* GENERATED by scripts/fetch-live.mjs at build time — do not edit by hand.
   Committed so the site works without a build; the build overwrites it.
   data.js overlays these onto its committed pegs, and falls back to the
   pegs if this file is missing or malformed. */
window.IAM_LIVE = {
  "rates": {
    "BHD": 1,
    "SAR": 9.973404,
    "AED": 9.767287,
    "QAR": 9.680851,
    "OMR": 1.022598,
    "KWD": 0.820636,
    "USD": 2.659574
  },
  "fetchedAt": "2026-08-06T19:27:14.137Z",
  "sourceUpdatedAt": "Thu, 06 Aug 2026 00:02:31 +0000",
  "source": "exchangerate-api.com"
};
