/* =========================================================================
   fetch-live.mjs — build-time live data fetch
   -------------------------------------------------------------------------
   Runs on Netlify before publish. Fetches FX rates and bakes them into
   iam-golf/js/live.js as a plain global, so the browser loads them with an
   ordinary <script> tag — no runtime fetch, no CORS, no loading flicker,
   and the page still works opened over file://.

   FAILURE POLICY: this script must never break a deploy and must never
   ship a bad price. Any failure — network, bad shape, implausible value —
   leaves the existing live.js untouched and exits 0. The site then falls
   back to the pegs committed in data.js, which are correct for every
   pegged currency anyway.
   ========================================================================= */

import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../kaz6-site/iam-golf/js/live.js");
const ENDPOINT = "https://open.er-api.com/v6/latest/BHD";
const TIMEOUT_MS = 15000;

/* The currencies the picker offers, with the committed peg as a sanity
   anchor. BHD/SAR/AED/QAR/OMR are hard USD pegs and must not move; KWD
   tracks a basket so it earns a wider band. A rate outside its band means
   the feed is wrong, not that the world changed. */
const EXPECTED = {
  SAR: { peg: 9.9734, tolerance: 0.02 },
  AED: { peg: 9.7673, tolerance: 0.02 },
  QAR: { peg: 9.6808, tolerance: 0.02 },
  OMR: { peg: 1.0226, tolerance: 0.02 },
  KWD: { peg: 0.8151, tolerance: 0.10 },
  USD: { peg: 2.6596, tolerance: 0.02 },
};

function bail(reason) {
  console.warn(`[fetch-live] SKIPPED — ${reason}`);
  console.warn(`[fetch-live] keeping existing ${existsSync(OUT) ? "live.js" : "(none — data.js pegs will be used)"}`);
  process.exit(0); // never fail the build
}

async function main() {
  let payload;
  try {
    const res = await fetch(ENDPOINT, { signal: AbortSignal.timeout(TIMEOUT_MS) });
    if (!res.ok) return bail(`HTTP ${res.status}`);
    payload = await res.json();
  } catch (err) {
    return bail(`fetch failed: ${err.message}`);
  }

  if (payload?.result !== "success" || !payload?.rates) return bail("unexpected response shape");
  if (payload.base_code !== "BHD") return bail(`base is ${payload.base_code}, expected BHD`);

  /* validate every rate before trusting any of them */
  const rates = { BHD: 1 };
  for (const [code, { peg, tolerance }] of Object.entries(EXPECTED)) {
    const v = payload.rates[code];
    if (typeof v !== "number" || !Number.isFinite(v) || v <= 0) return bail(`${code} missing or not a positive number`);
    const drift = Math.abs(v - peg) / peg;
    if (drift > tolerance) {
      return bail(`${code} = ${v} is ${(drift * 100).toFixed(2)}% off its ${peg} anchor (max ${(tolerance * 100).toFixed(0)}%)`);
    }
    rates[code] = v;
  }

  const out = {
    rates,
    fetchedAt: new Date().toISOString(),
    sourceUpdatedAt: payload.time_last_update_utc || null,
    source: "exchangerate-api.com",
  };

  const banner =
    "/* GENERATED by scripts/fetch-live.mjs at build time — do not edit by hand.\n" +
    "   Committed so the site works without a build; the build overwrites it.\n" +
    "   data.js overlays these onto its committed pegs, and falls back to the\n" +
    "   pegs if this file is missing or malformed. */\n";

  writeFileSync(OUT, `${banner}window.IAM_LIVE = ${JSON.stringify(out, null, 2)};\n`);

  const drifts = Object.entries(EXPECTED)
    .map(([c, { peg }]) => `${c} ${(((rates[c] - peg) / peg) * 100).toFixed(3)}%`)
    .join("  ");
  console.log(`[fetch-live] wrote ${OUT}`);
  console.log(`[fetch-live] source updated ${out.sourceUpdatedAt}`);
  console.log(`[fetch-live] drift vs committed pegs: ${drifts}`);
}

main().catch((e) => bail(`unhandled: ${e.message}`));
