/*
 * 38-0 La Liga — match database
 * Real clubs/players used descriptively. Ratings are an independent interpretation.
 * line = GK | DEF | MID | ATT ; player = [name, line, rating]
 */

var CLUBS=[
 {club:"Barcelona",abbr:"BAR",color:"#A50044",color2:"#004D98",text:"#fff",seasons:[
   {season:"1996-97",players:[["Vítor Baía","GK",80],["Fernando Couto","DEF",80],["Laurent Blanc","DEF",82],["Abelardo","DEF",80],["Sergi Barjuán","DEF",79],["Albert Ferrer","DEF",78],["Pep Guardiola","MID",84],["Luis Enrique","MID",83],["Iván de la Peña","MID",80],["Gheorghe Popescu","MID",80],["Luís Figo","MID",86],["Ronaldo Nazário","ATT",91],["Giovanni","ATT",81],["Pizzi","ATT",79]]},
   {season:"1998-99",players:[["Ruud Hesp","GK",78],["Michael Reiziger","DEF",79],["Frank de Boer","DEF",82],["Abelardo","DEF",80],["Sergi Barjuán","DEF",79],["Albert Ferrer","DEF",78],["Pep Guardiola","MID",85],["Luís Figo","MID",88],["Phillip Cocu","MID",82],["Jari Litmanen","MID",82],["Luis Enrique","MID",83],["Rivaldo","ATT",90],["Patrick Kluivert","ATT",85],["Sonny Anderson","ATT",80]]},
   {season:"2005-06",players:[["Víctor Valdés","GK",83],["Juliano Belletti","DEF",80],["Carles Puyol","DEF",86],["Rafael Márquez","DEF",83],["Gio van Bronckhorst","DEF",80],["Oleguer","DEF",77],["Deco","MID",86],["Xavi","MID",85],["Edmílson","MID",79],["Andrés Iniesta","MID",81],["Mark van Bommel","MID",79],["Ronaldinho","ATT",93],["Samuel Eto'o","ATT",88],["Ludovic Giuly","ATT",80],["Henrik Larsson","ATT",82]]},
   {season:"2008-09",players:[["Víctor Valdés","GK",86],["Dani Alves","DEF",88],["Carles Puyol","DEF",87],["Gerard Piqué","DEF",85],["Rafael Márquez","DEF",82],["Éric Abidal","DEF",84],["Xavi","MID",91],["Andrés Iniesta","MID",90],["Sergio Busquets","MID",84],["Yaya Touré","MID",84],["Seydou Keita","MID",80],["Lionel Messi","ATT",93],["Samuel Eto'o","ATT",89],["Thierry Henry","ATT",86]]},
   {season:"2009-10",players:[["Víctor Valdés","GK",86],["Dani Alves","DEF",87],["Carles Puyol","DEF",86],["Gerard Piqué","DEF",85],["Maxwell","DEF",79],["Gabriel Milito","DEF",78],["Xavi","MID",91],["Andrés Iniesta","MID",90],["Sergio Busquets","MID",84],["Yaya Touré","MID",84],["Seydou Keita","MID",80],["Lionel Messi","ATT",94],["Zlatan Ibrahimović","ATT",88],["Pedro","ATT",81],["Thierry Henry","ATT",83]]},
   {season:"2015-16",players:[["Marc-André ter Stegen","GK",85],["Dani Alves","DEF",85],["Gerard Piqué","DEF",86],["Javier Mascherano","DEF",84],["Jordi Alba","DEF",85],["Marc Bartra","DEF",79],["Sergio Busquets","MID",87],["Andrés Iniesta","MID",88],["Ivan Rakitić","MID",85],["Rafinha","MID",80],["Sergi Roberto","MID",80],["Lionel Messi","ATT",95],["Luis Suárez","ATT",91],["Neymar","ATT",90],["Arda Turan","ATT",82]]},
   {season:"2016-17",players:[["Marc-André ter Stegen","GK",86],["Jordi Alba","DEF",85],["Gerard Piqué","DEF",86],["Samuel Umtiti","DEF",81],["Sergi Roberto","DEF",81],["Javier Mascherano","DEF",83],["Sergio Busquets","MID",86],["Andrés Iniesta","MID",86],["Ivan Rakitić","MID",84],["Denis Suárez","MID",79],["André Gomes","MID",79],["Lionel Messi","ATT",95],["Luis Suárez","ATT",90],["Neymar","ATT",90],["Paco Alcácer","ATT",79]]},
   {season:"2010-11",players:[["Víctor Valdés","GK",86],["Dani Alves","DEF",88],["Gerard Piqué","DEF",87],["Carles Puyol","DEF",86],["Éric Abidal","DEF",83],["Adriano","DEF",79],["Xavi","MID",92],["Andrés Iniesta","MID",91],["Sergio Busquets","MID",85],["Javier Mascherano","MID",84],["Seydou Keita","MID",80],["Lionel Messi","ATT",94],["David Villa","ATT",89],["Pedro","ATT",83]]},
   {season:"2012-13",players:[["Víctor Valdés","GK",85],["Dani Alves","DEF",86],["Gerard Piqué","DEF",86],["Carles Puyol","DEF",84],["Jordi Alba","DEF",84],["Javier Mascherano","DEF",84],["Xavi","MID",88],["Andrés Iniesta","MID",89],["Sergio Busquets","MID",86],["Cesc Fàbregas","MID",84],["Thiago","MID",81],["Lionel Messi","ATT",95],["David Villa","ATT",84],["Pedro","ATT",82],["Alexis Sánchez","ATT",81]]},
   {season:"2014-15",players:[["Marc-André ter Stegen","GK",84],["Claudio Bravo","GK",84],["Dani Alves","DEF",86],["Gerard Piqué","DEF",87],["Javier Mascherano","DEF",85],["Jordi Alba","DEF",86],["Xavi","MID",86],["Andrés Iniesta","MID",89],["Sergio Busquets","MID",87],["Ivan Rakitić","MID",85],["Lionel Messi","ATT",95],["Luis Suárez","ATT",91],["Neymar","ATT",90],["Pedro","ATT",81]]},
   {season:"2018-19",players:[["Marc-André ter Stegen","GK",88],["Sergi Roberto","DEF",80],["Gerard Piqué","DEF",86],["Clément Lenglet","DEF",82],["Jordi Alba","DEF",86],["Nélson Semedo","DEF",79],["Sergio Busquets","MID",86],["Arthur","MID",80],["Arturo Vidal","MID",81],["Ivan Rakitić","MID",84],["Philippe Coutinho","MID",83],["Lionel Messi","ATT",94],["Luis Suárez","ATT",88],["Ousmane Dembélé","ATT",82]]},
   {season:"2022-23",players:[["Marc-André ter Stegen","GK",88],["Jules Koundé","DEF",84],["Ronald Araújo","DEF",84],["Andreas Christensen","DEF",81],["Jordi Alba","DEF",81],["Alejandro Balde","DEF",79],["Sergio Busquets","MID",82],["Pedri","MID",85],["Gavi","MID",83],["Frenkie de Jong","MID",85],["Franck Kessié","MID",80],["Robert Lewandowski","ATT",89],["Raphinha","ATT",83],["Ousmane Dembélé","ATT",84]]}
 ]},
 {club:"Real Madrid",abbr:"RMA",color:"#D9C25C",color2:"#FFFFFF",text:"#241407",seasons:[
   {season:"1999-00",players:[["Iker Casillas","GK",80],["Roberto Carlos","DEF",88],["Fernando Hierro","DEF",85],["Aitor Karanka","DEF",79],["Míchel Salgado","DEF",80],["Iván Campo","DEF",78],["Fernando Redondo","MID",87],["Steve McManaman","MID",81],["Guti","MID",79],["Sávio","MID",79],["Raúl","ATT",87],["Nicolas Anelka","ATT",81],["Fernando Morientes","ATT",83]]},
   {season:"2002-03",players:[["Iker Casillas","GK",86],["Roberto Carlos","DEF",89],["Fernando Hierro","DEF",85],["Iván Helguera","DEF",82],["Míchel Salgado","DEF",81],["Zinedine Zidane","MID",94],["Luís Figo","MID",90],["Claude Makélélé","MID",85],["Steve McManaman","MID",82],["Guti","MID",81],["Ronaldo Nazário","ATT",93],["Raúl","ATT",89],["Fernando Morientes","ATT",84]]},
   {season:"2003-04",players:[["Iker Casillas","GK",86],["Roberto Carlos","DEF",88],["Iván Helguera","DEF",81],["Míchel Salgado","DEF",80],["Raúl Bravo","DEF",77],["Zinedine Zidane","MID",93],["David Beckham","MID",88],["Luís Figo","MID",88],["Guti","MID",81],["Santiago Solari","MID",79],["Ronaldo Nazário","ATT",92],["Raúl","ATT",88],["Fernando Morientes","ATT",82]]},
   {season:"2007-08",players:[["Iker Casillas","GK",87],["Sergio Ramos","DEF",84],["Fabio Cannavaro","DEF",84],["Pepe","DEF",82],["Gabriel Heinze","DEF",79],["Míchel Salgado","DEF",78],["Wesley Sneijder","MID",84],["Guti","MID",81],["Mahamadou Diarra","MID",80],["Arjen Robben","MID",85],["Robinho","MID",83],["Ruud van Nistelrooy","ATT",86],["Raúl","ATT",84],["Gonzalo Higuaín","ATT",80]]},
   {season:"2009-10",players:[["Iker Casillas","GK",88],["Sergio Ramos","DEF",86],["Pepe","DEF",82],["Raúl Albiol","DEF",80],["Marcelo","DEF",81],["Álvaro Arbeloa","DEF",79],["Xabi Alonso","MID",85],["Lassana Diarra","MID",80],["Kaká","MID",86],["Guti","MID",80],["Cristiano Ronaldo","ATT",92],["Karim Benzema","ATT",82],["Gonzalo Higuaín","ATT",83]]},
   {season:"2011-12",players:[["Iker Casillas","GK",89],["Sergio Ramos","DEF",88],["Pepe","DEF",85],["Marcelo","DEF",84],["Fábio Coentrão","DEF",80],["Álvaro Arbeloa","DEF",79],["Xabi Alonso","MID",87],["Mesut Özil","MID",87],["Ángel Di María","MID",85],["Sami Khedira","MID",83],["Kaká","MID",84],["Cristiano Ronaldo","ATT",95],["Karim Benzema","ATT",86],["Gonzalo Higuaín","ATT",85]]},
   {season:"2014-15",players:[["Iker Casillas","GK",84],["Dani Carvajal","DEF",82],["Sergio Ramos","DEF",88],["Pepe","DEF",84],["Marcelo","DEF",86],["Nacho","DEF",79],["Toni Kroos","MID",88],["Luka Modrić","MID",88],["James Rodríguez","MID",85],["Isco","MID",83],["Asier Illarramendi","MID",77],["Cristiano Ronaldo","ATT",95],["Gareth Bale","ATT",88],["Karim Benzema","ATT",86],["Javier Hernández","ATT",80]]},
   {season:"2019-20",players:[["Thibaut Courtois","GK",88],["Dani Carvajal","DEF",84],["Sergio Ramos","DEF",88],["Raphaël Varane","DEF",85],["Marcelo","DEF",83],["Ferland Mendy","DEF",80],["Nacho","DEF",79],["Casemiro","MID",86],["Toni Kroos","MID",87],["Luka Modrić","MID",86],["Federico Valverde","MID",82],["Isco","MID",81],["Karim Benzema","ATT",89],["Eden Hazard","ATT",84],["Vinícius Júnior","ATT",82],["Rodrygo","ATT",80]]},
   {season:"2013-14",players:[["Iker Casillas","GK",85],["Diego López","GK",82],["Dani Carvajal","DEF",81],["Sergio Ramos","DEF",88],["Pepe","DEF",84],["Marcelo","DEF",85],["Fábio Coentrão","DEF",79],["Luka Modrić","MID",87],["Xabi Alonso","MID",84],["Ángel Di María","MID",86],["Sami Khedira","MID",82],["Isco","MID",81],["Cristiano Ronaldo","ATT",95],["Karim Benzema","ATT",86],["Gareth Bale","ATT",88]]},
   {season:"2016-17",players:[["Keylor Navas","GK",84],["Dani Carvajal","DEF",84],["Sergio Ramos","DEF",89],["Raphaël Varane","DEF",85],["Marcelo","DEF",87],["Pepe","DEF",83],["Nacho","DEF",80],["Luka Modrić","MID",90],["Toni Kroos","MID",89],["Casemiro","MID",85],["Isco","MID",85],["Mateo Kovačić","MID",80],["Cristiano Ronaldo","ATT",94],["Karim Benzema","ATT",87],["Gareth Bale","ATT",88]]},
   {season:"2017-18",players:[["Keylor Navas","GK",84],["Dani Carvajal","DEF",84],["Sergio Ramos","DEF",89],["Raphaël Varane","DEF",85],["Marcelo","DEF",86],["Nacho","DEF",80],["Luka Modrić","MID",95],["Toni Kroos","MID",90],["Casemiro","MID",86],["Isco","MID",85],["Marco Asensio","MID",82],["Mateo Kovačić","MID",80],["Cristiano Ronaldo","ATT",94],["Karim Benzema","ATT",84],["Gareth Bale","ATT",86]]},
   {season:"2021-22",players:[["Thibaut Courtois","GK",89],["Dani Carvajal","DEF",83],["Éder Militão","DEF",84],["David Alaba","DEF",85],["Ferland Mendy","DEF",81],["Nacho","DEF",80],["Casemiro","MID",85],["Luka Modrić","MID",86],["Toni Kroos","MID",86],["Federico Valverde","MID",83],["Marco Asensio","MID",80],["Karim Benzema","ATT",91],["Vinícius Júnior","ATT",87],["Rodrygo","ATT",83]]},
   {season:"2023-24",players:[["Thibaut Courtois","GK",89],["Andriy Lunin","GK",80],["Dani Carvajal","DEF",86],["Antonio Rüdiger","DEF",86],["Nacho","DEF",82],["Ferland Mendy","DEF",82],["Federico Valverde","MID",87],["Jude Bellingham","MID",90],["Toni Kroos","MID",87],["Aurélien Tchouaméni","MID",84],["Eduardo Camavinga","MID",84],["Vinícius Júnior","ATT",91],["Rodrygo","ATT",86],["Joselu","ATT",79]]}
 ]},
 {club:"Atlético Madrid",abbr:"ATM",color:"#C8102E",color2:"#1A2A6C",text:"#fff",seasons:[
   {season:"1995-96",players:[["José Francisco Molina","GK",81],["Roberto Solozábal","DEF",79],["Toni","DEF",79],["Delfí Geli","DEF",78],["Juan Vizcaíno","MID",79],["Diego Simeone","MID",85],["José Luis Caminero","MID",83],["Milinko Pantić","MID",82],["Kiko","ATT",84],["Lyuboslav Penev","ATT",82],["Juan Esnáider","ATT",80]]},
   {season:"2009-10",players:[["David de Gea","GK",80],["Antonio López","DEF",78],["Tomáš Ujfaluši","DEF",79],["Álvaro Domínguez","DEF",78],["Juanito","DEF",78],["Luis Perea","DEF",79],["Simão","MID",81],["José Antonio Reyes","MID",81],["Tiago","MID",79],["Raúl García","MID",78],["Sergio Agüero","ATT",86],["Diego Forlán","ATT",84]]},
   {season:"2013-14",players:[["Thibaut Courtois","GK",87],["Juanfran","DEF",82],["Diego Godín","DEF",87],["Miranda","DEF",84],["Filipe Luís","DEF",84],["Toby Alderweireld","DEF",80],["Gabi","MID",81],["Tiago","MID",80],["Koke","MID",84],["Arda Turan","MID",84],["Raúl García","MID",79],["Diego Costa","ATT",88],["David Villa","ATT",83],["Diego Ribas","ATT",80]]},
   {season:"2015-16",players:[["Jan Oblak","GK",86],["Juanfran","DEF",81],["Diego Godín","DEF",87],["José Giménez","DEF",81],["Filipe Luís","DEF",83],["Stefan Savić","DEF",80],["Gabi","MID",81],["Koke","MID",84],["Saúl","MID",81],["Augusto Fernández","MID",78],["Yannick Carrasco","MID",81],["Antoine Griezmann","ATT",88],["Fernando Torres","ATT",81],["Jackson Martínez","ATT",79]]},
   {season:"2017-18",players:[["Jan Oblak","GK",88],["Juanfran","DEF",81],["Diego Godín","DEF",86],["José Giménez","DEF",82],["Lucas Hernández","DEF",82],["Filipe Luís","DEF",82],["Gabi","MID",80],["Koke","MID",84],["Saúl","MID",82],["Thomas Partey","MID",80],["Yannick Carrasco","MID",81],["Antoine Griezmann","ATT",89],["Diego Costa","ATT",85],["Kevin Gameiro","ATT",80],["Ángel Correa","ATT",80]]},
   {season:"2018-19",players:[["Jan Oblak","GK",90],["Juanfran","DEF",80],["Diego Godín","DEF",85],["José Giménez","DEF",83],["Lucas Hernández","DEF",82],["Filipe Luís","DEF",81],["Koke","MID",84],["Rodri","MID",84],["Saúl","MID",82],["Thomas Partey","MID",82],["Thomas Lemar","MID",80],["Antoine Griezmann","ATT",89],["Diego Costa","ATT",83],["Álvaro Morata","ATT",81],["Ángel Correa","ATT",80]]},
   {season:"2023-24",players:[["Jan Oblak","GK",88],["Nahuel Molina","DEF",80],["Axel Witsel","DEF",79],["José Giménez","DEF",82],["Mario Hermoso","DEF",79],["Reinildo","DEF",78],["Koke","MID",82],["Rodrigo De Paul","MID",83],["Marcos Llorente","MID",83],["Pablo Barrios","MID",78],["Saúl","MID",79],["Antoine Griezmann","ATT",88],["Álvaro Morata","ATT",83],["Memphis Depay","ATT",81],["Ángel Correa","ATT",80]]},
   {season:"2020-21",players:[["Jan Oblak","GK",90],["Kieran Trippier","DEF",82],["Stefan Savić","DEF",82],["José Giménez","DEF",83],["Mario Hermoso","DEF",80],["Renan Lodi","DEF",79],["Koke","MID",84],["Marcos Llorente","MID",85],["Saúl","MID",82],["Yannick Carrasco","MID",83],["Thomas Lemar","MID",79],["Luis Suárez","ATT",86],["João Félix","ATT",83],["Ángel Correa","ATT",81]]}
 ]},
 {club:"Valencia",abbr:"VAL",color:"#F18E00",color2:"#000000",text:"#241407",seasons:[
   {season:"1999-00",players:[["Santiago Cañizares","GK",84],["Jocelyn Angloma","DEF",79],["Mauricio Pellegrino","DEF",78],["Amedeo Carboni","DEF",78],["Miroslav Đukić","DEF",78],["Gaizka Mendieta","MID",86],["Kily González","MID",80],["Gerard López","MID",80],["Francisco Farinós","MID",78],["Claudio López","ATT",85],["Adrian Ilie","ATT",80],["Juan Sánchez","ATT",78]]},
   {season:"2001-02",players:[["Santiago Cañizares","GK",85],["Carlos Marchena","DEF",80],["Roberto Ayala","DEF",85],["Mauricio Pellegrino","DEF",79],["Amedeo Carboni","DEF",78],["Curro Torres","DEF",76],["Rubén Baraja","MID",83],["David Albelda","MID",82],["Pablo Aimar","MID",86],["Vicente","MID",83],["Kily González","MID",80],["Mista","ATT",81],["Juan Sánchez","ATT",78],["John Carew","ATT",79]]},
   {season:"2009-10",players:[["César Sánchez","GK",80],["Miguel","DEF",78],["Carlos Marchena","DEF",80],["Jérémy Mathieu","DEF",80],["David Navarro","DEF",77],["Alexis","DEF",77],["David Albelda","MID",80],["Rubén Baraja","MID",80],["David Silva","MID",86],["Juan Mata","MID",83],["Éver Banega","MID",80],["David Villa","ATT",89],["Vicente","ATT",80],["Pablo Hernández","ATT",78]]},
   {season:"2003-04",players:[["Santiago Cañizares","GK",84],["Curro Torres","DEF",77],["Roberto Ayala","DEF",85],["Carlos Marchena","DEF",81],["Amedeo Carboni","DEF",78],["Emiliano Moretti","DEF",77],["David Albelda","MID",82],["Rubén Baraja","MID",84],["Vicente","MID",84],["Pablo Aimar","MID",85],["Francisco Rufete","MID",77],["Mista","ATT",82],["Ricardo Oliveira","ATT",80],["Juan Sánchez","ATT",78]]}
 ]},
 {club:"Sevilla",abbr:"SEV",color:"#C8202F",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"2006-07",players:[["Andrés Palop","GK",81],["Dani Alves","DEF",84],["Javi Navarro","DEF",78],["Julien Escudé","DEF",79],["Aitor Ocio","DEF",76],["David Castedo","DEF",76],["Christian Poulsen","MID",79],["Renato","MID",78],["Jesús Navas","MID",82],["Seydou Keita","MID",80],["Diego Capel","MID",76],["Frédéric Kanouté","ATT",85],["Luís Fabiano","ATT",83],["Enzo Maresca","ATT",78]]},
   {season:"2009-10",players:[["Andrés Palop","GK",80],["Fernando Navarro","DEF",78],["Sébastien Squillaci","DEF",80],["Julien Escudé","DEF",79],["Abdoulay Konko","DEF",77],["Didier Zokora","MID",79],["Renato","MID",77],["Jesús Navas","MID",83],["Diego Capel","MID",77],["Diego Perotti","MID",78],["Luís Fabiano","ATT",84],["Frédéric Kanouté","ATT",84],["Álvaro Negredo","ATT",83]]},
   {season:"2015-16",players:[["Sergio Rico","GK",79],["David Soria","GK",77],["Mariano","DEF",78],["Adil Rami","DEF",79],["Nicolás Pareja","DEF",78],["Coke","DEF",77],["Benoît Trémoulinas","DEF",77],["Steven N'Zonzi","MID",82],["Grzegorz Krychowiak","MID",82],["Éver Banega","MID",83],["Vitolo","MID",81],["Kevin Gameiro","ATT",82],["Yevhen Konoplyanka","ATT",80],["José Antonio Reyes","ATT",79]]},
   {season:"2016-17",players:[["Sergio Rico","GK",79],["Mariano","DEF",78],["Adil Rami","DEF",79],["Clément Lenglet","DEF",80],["Sergio Escudero","DEF",78],["Gabriel Mercado","DEF",78],["Steven N'Zonzi","MID",82],["Éver Banega","MID",83],["Vitolo","MID",81],["Samir Nasri","MID",81],["Vicente Iborra","MID",79],["Wissam Ben Yedder","ATT",81],["Pablo Sarabia","ATT",81],["Stevan Jovetić","ATT",80],["Joaquín Correa","ATT",79]]},
   {season:"2019-20",players:[["Tomáš Vaclík","GK",80],["Bono","GK",81],["Jesús Navas","DEF",80],["Diego Carlos","DEF",83],["Jules Koundé","DEF",83],["Sergio Reguilón","DEF",81],["Fernando","MID",81],["Éver Banega","MID",84],["Joan Jordán","MID",79],["Suso","MID",80],["Lucas Ocampos","ATT",83],["Youssef En-Nesyri","ATT",79],["Luuk de Jong","ATT",78]]}
 ]},
 {club:"Villarreal",abbr:"VIL",color:"#F2C300",color2:"#005187",text:"#241407",seasons:[
   {season:"2005-06",players:[["Sebastián Viera","GK",78],["Javi Venta","DEF",77],["Gonzalo Rodríguez","DEF",80],["Quique Álvarez","DEF",77],["Rodolfo Arruabarrena","DEF",76],["Marcos Senna","MID",82],["Juan Román Riquelme","MID",88],["Santi Cazorla","MID",80],["Josico","MID",77],["Diego Forlán","ATT",85],["José Mari","ATT",77],["Guille Franco","ATT",77]]},
   {season:"2007-08",players:[["Diego López","GK",80],["Javi Venta","DEF",77],["Gonzalo Rodríguez","DEF",80],["Diego Godín","DEF",80],["Joan Capdevila","DEF",80],["Marcos Senna","MID",82],["Santi Cazorla","MID",82],["Robert Pirès","MID",82],["Bruno Soriano","MID",78],["Cani","MID",78],["Giuseppe Rossi","ATT",82],["Nihat Kahveci","ATT",80],["Guille Franco","ATT",77]]},
   {season:"2015-16",players:[["Sergio Asenjo","GK",81],["Mario Gaspar","DEF",78],["Mateo Musacchio","DEF",80],["Víctor Ruiz","DEF",78],["Jaume Costa","DEF",78],["Bruno Soriano","MID",80],["Manu Trigueros","MID",78],["Tomás Pina","MID",77],["Denis Suárez","MID",80],["Samu Castillejo","MID",78],["Cédric Bakambu","ATT",80],["Roberto Soldado","ATT",79],["Adrián López","ATT",78]]},
   {season:"2020-21",players:[["Gerónimo Rulli","GK",82],["Mario Gaspar","DEF",78],["Pau Torres","DEF",83],["Raúl Albiol","DEF",81],["Alfonso Pedraza","DEF",78],["Juan Foyth","DEF",80],["Dani Parejo","MID",84],["Étienne Capoue","MID",82],["Francis Coquelin","MID",79],["Manu Trigueros","MID",78],["Gerard Moreno","ATT",85],["Paco Alcácer","ATT",81],["Samuel Chukwueze","ATT",80]]}
 ]},
 {club:"Athletic Bilbao",abbr:"ATH",color:"#9E2A2B",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1983-84",players:[["Andoni Zubizarreta","GK",84],["Andoni Goikoetxea","DEF",79],["Genar Andrinúa","DEF",78],["Santiago Urkiaga","DEF",78],["Patxi Liceranzu","DEF",77],["Manuel Sarabia","MID",82],["Miguel de Andrés","MID",78],["Andoni Gallego","MID",78],["Estanislao Argote","MID",79],["Dani","ATT",81],["Ismael Urtubi","ATT",78]]},
   {season:"2011-12",players:[["Gorka Iraizoz","GK",78],["Andoni Iraola","DEF",79],["Fernando Amorebieta","DEF",78],["Javi Martínez","DEF",84],["Jon Aurtenetxe","DEF",75],["Ander Herrera","MID",81],["Óscar de Marcos","MID",78],["Markel Susaeta","MID",79],["Iker Muniain","MID",80],["Ander Iturraspe","MID",77],["Fernando Llorente","ATT",84],["Ibai Gómez","ATT",76],["Gaizka Toquero","ATT",75]]},
   {season:"2015-16",players:[["Gorka Iraizoz","GK",78],["Óscar de Marcos","DEF",78],["Aymeric Laporte","DEF",82],["Mikel San José","DEF",79],["Eneko Bóveda","DEF",76],["Ander Iturraspe","MID",78],["Beñat Etxebarria","MID",79],["Markel Susaeta","MID",79],["Iker Muniain","MID",80],["Raúl García","MID",80],["Aritz Aduriz","ATT",84],["Iñaki Williams","ATT",80],["Sabin Merino","ATT",76]]},
   {season:"2023-24",players:[["Unai Simón","GK",84],["Óscar de Marcos","DEF",79],["Dani Vivian","DEF",80],["Yeray Álvarez","DEF",79],["Yuri Berchiche","DEF",79],["Iñigo Lekue","DEF",76],["Mikel Vesga","MID",77],["Oihan Sancet","MID",81],["Ander Herrera","MID",78],["Iker Muniain","MID",79],["Iñaki Williams","ATT",82],["Nico Williams","ATT",83],["Gorka Guruzeta","ATT",78],["Álex Berenguer","ATT",79]]}
 ]},
 {club:"Real Sociedad",abbr:"RSO",color:"#1E78C8",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1981-82",players:[["Luis Arconada","GK",85],["Alberto Górriz","DEF",79],["Ignacio Kortabarria","DEF",78],["Inaxio Gajate","DEF",77],["Antton Celayeta","DEF",76],["Jesús María Zamora","MID",80],["Periko Alonso","MID",80],["José Mari Idígoras","MID",77],["Diego","MID",77],["Roberto López Ufarte","ATT",82],["Jesús María Satrústegui","ATT",81]]},
   {season:"2002-03",players:[["Sander Westerveld","GK",80],["Bjørn Tore Kvarme","DEF",77],["Agustín Aranzábal","DEF",78],["Igor Gabilondo","DEF",76],["Boris","DEF",75],["Xabi Alonso","MID",84],["Mikel Aranburu","MID",77],["Valeri Karpin","MID",80],["Francisco de Pedro","MID",81],["Darko Kovačević","ATT",83],["Nihat Kahveci","ATT",82]]},
   {season:"2012-13",players:[["Claudio Bravo","GK",81],["Carlos Martínez","DEF",77],["Iñigo Martínez","DEF",80],["Mikel González","DEF",77],["Alberto de la Bella","DEF",76],["Asier Illarramendi","MID",80],["Rubén Pardo","MID",77],["Markel Bergara","MID",77],["Xabi Prieto","MID",80],["Carlos Vela","MID",82],["Antoine Griezmann","ATT",82],["Imanol Agirretxe","ATT",78],["Chory Castro","ATT",78]]},
   {season:"2022-23",players:[["Álex Remiro","GK",82],["Andoni Gorosabel","DEF",77],["Robin Le Normand","DEF",82],["Igor Zubeldia","DEF",79],["Aihen Muñoz","DEF",77],["Martín Zubimendi","MID",82],["Mikel Merino","MID",82],["Brais Méndez","MID",80],["David Silva","MID",83],["Takefusa Kubo","MID",81],["Mikel Oyarzabal","ATT",84],["Alexander Sørloth","ATT",79]]}
 ]},
 {club:"Real Betis",abbr:"BET",color:"#1B9C57",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"2004-05",players:[["Toni Doblas","GK",78],["Juanito","DEF",79],["Arzu","DEF",77],["David Rivas","DEF",76],["Juan José Cañas","DEF",76],["Joaquín","MID",84],["Marcos Assunção","MID",80],["Denílson","MID",80],["Fernando","MID",78],["Ricardo Oliveira","ATT",81],["Edu","ATT",78],["Dani","ATT",77]]},
   {season:"2021-22",players:[["Rui Silva","GK",80],["Claudio Bravo","GK",80],["Héctor Bellerín","DEF",79],["Marc Bartra","DEF",80],["Germán Pezzella","DEF",79],["Álex Moreno","DEF",79],["Guido Rodríguez","MID",81],["William Carvalho","MID",80],["Sergio Canales","MID",82],["Nabil Fekir","MID",84],["Juanmi","ATT",78],["Borja Iglesias","ATT",79],["Willian José","ATT",78]]}
 ]},
 {club:"Deportivo",abbr:"DEP",color:"#2A5CAA",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1999-00",players:[["Francisco Molina","GK",80],["Enrique Romero","DEF",77],["Nourdin Naybet","DEF",81],["Donato","DEF",78],["Manuel Pablo","DEF",79],["Mauro Silva","MID",82],["Djalminha","MID",84],["Fran","MID",82],["Víctor Sánchez","MID",78],["Sergio","MID",77],["Roy Makaay","ATT",84],["Diego Tristán","ATT",82],["Pauleta","ATT",82]]},
   {season:"2001-02",players:[["Francisco Molina","GK",80],["Nourdin Naybet","DEF",80],["Hélder","DEF",78],["Manuel Pablo","DEF",79],["Joan Capdevila","DEF",79],["Mauro Silva","MID",80],["Juan Carlos Valerón","MID",83],["Djalminha","MID",82],["Sergio","MID",78],["Víctor Sánchez","MID",78],["Diego Tristán","ATT",83],["Roy Makaay","ATT",84],["Walter Pandiani","ATT",79]]},
   {season:"2003-04",players:[["Francisco Molina","GK",80],["Nourdin Naybet","DEF",80],["Jorge Andrade","DEF",79],["Manuel Pablo","DEF",79],["Joan Capdevila","DEF",80],["Lionel Scaloni","DEF",78],["Mauro Silva","MID",80],["Juan Carlos Valerón","MID",84],["Sergio","MID",78],["Aldo Duscher","MID",78],["Diego Tristán","ATT",81],["Walter Pandiani","ATT",80],["Albert Luque","ATT",80]]}
 ]},
 {club:"Celta Vigo",abbr:"CEL",color:"#8AC6E8",color2:"#C8102E",text:"#0c2a3a",seasons:[
   {season:"2002-03",players:[["Pablo Cavallero","GK",80],["Eduardo Berizzo","DEF",78],["Fernando Cáceres","DEF",77],["Vágner","DEF",77],["Juanfran","DEF",77],["Aleksandr Mostovói","MID",84],["Valeri Karpin","MID",82],["Edu","MID",78],["Doriva","MID",77],["Benni McCarthy","ATT",79],["Gustavo López","ATT",79],["Jesuli","ATT",77]]},
   {season:"2016-17",players:[["Sergio Álvarez","GK",78],["Hugo Mallo","DEF",78],["Gustavo Cabral","DEF",77],["Sergi Gómez","DEF",78],["Jonny","DEF",78],["Daniel Wass","MID",78],["Nemanja Radoja","MID",76],["Pablo Hernández","MID",78],["Iago Aspas","ATT",84],["John Guidetti","ATT",78],["Pione Sisto","ATT",77]]}
 ]},
 {club:"Espanyol",abbr:"ESP",color:"#1F6BB8",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"2006-07",players:[["Carlos Kameni","GK",79],["Jordi Lopo","DEF",76],["Daniel Jarque","DEF",78],["David García","DEF",76],["Moisés Hurtado","DEF",76],["Iván de la Peña","MID",81],["Ito","MID",77],["Pablo Zabaleta","MID",78],["Luis García","MID",78],["Raúl Tamudo","ATT",81],["Walter Pandiani","ATT",79],["Coro","ATT",76]]}
 ]},
 {club:"Getafe",abbr:"GET",color:"#1E5BA8",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"2007-08",players:[["Roberto Abbondanzieri","GK",79],["David Belenguer","DEF",77],["Cata Díaz","DEF",78],["Alexis","DEF",77],["Mané","DEF",76],["Mario Cotelo","MID",76],["Pablo Hernández","MID",78],["Javier Casquero","MID",77],["Francesco Celestini","MID",76],["Manu del Moral","ATT",77],["Ikechukwu Uche","ATT",78],["Braulio","ATT",76]]}
 ]},
 {club:"Málaga",abbr:"MAL",color:"#00A2E0",color2:"#FFFFFF",text:"#06283a",seasons:[
   {season:"2012-13",players:[["Willy Caballero","GK",80],["Weligton","DEF",78],["Martín Demichelis","DEF",80],["Jesús Gámez","DEF",77],["Antunes","DEF",77],["Jérémy Toulalan","MID",80],["Isco","MID",82],["Joaquín","MID",80],["Ignacio Camacho","MID",77],["Manuel Iturra","MID",76],["Javier Saviola","ATT",79],["Júlio Baptista","ATT",79],["Roque Santa Cruz","ATT",78]]}
 ]},
 {club:"Zaragoza",abbr:"ZAR",color:"#D0103A",color2:"#1A3A8F",text:"#fff",seasons:[
   {season:"2003-04",players:[["César Sánchez","GK",79],["Álvaro","DEF",77],["Soldevilla","DEF",76],["Toledo","DEF",76],["Yordi","DEF",76],["Andrés D'Alessandro","MID",81],["Gabi","MID",77],["Juanele","MID",78],["Movilla","MID",77],["David Villa","ATT",82],["Diego Milito","ATT",83],["Luciano Galletti","ATT",80]]}
 ]},
 {club:"Mallorca",abbr:"MLL",color:"#7A1A2B",color2:"#C8102E",text:"#fff",seasons:[
   {season:"2002-03",players:[["Leo Franco","GK",80],["Miguel Ángel Nadal","DEF",79],["Lussenhoff","DEF",77],["Poli","DEF",76],["Fernando Niño","DEF",76],["Marcos","MID",77],["Ariel Ibagaza","MID",79],["Vicente Engonga","MID",78],["Novo","MID",77],["Samuel Eto'o","ATT",84],["Albert Luque","ATT",78],["Walter Pandiani","ATT",78]]}
 ]},
 {club:"Osasuna",abbr:"OSA",color:"#B11A1A",color2:"#1A3A8F",text:"#fff",seasons:[
   {season:"2006-07",players:[["Ricardo","GK",78],["César Cruchaga","DEF",77],["Josetxo","DEF",77],["Cuéllar","DEF",75],["Miguel Flaño","DEF",75],["Patxi Puñal","MID",78],["Javad Nekounam","MID",78],["Juanfran","MID",77],["David López","MID",77],["Pierre Webó","ATT",78],["Soldado","ATT",77],["Romeo","ATT",76]]}
 ]},
 {club:"Levante",abbr:"LEV",color:"#2A4A9C",color2:"#8E2E5E",text:"#fff",seasons:[
   {season:"2011-12",players:[["Keylor Navas","GK",80],["Sergio Ballesteros","DEF",77],["David Navarro","DEF",77],["Juanfran","DEF",76],["Héctor Rodas","DEF",75],["Vicente Iborra","MID",78],["Xavi Torres","MID",76],["Valdo","MID",76],["Pedro Ríos","MID",75],["Arouna Koné","ATT",80],["Rubén Suárez","ATT",76],["Nabil El Zhar","ATT",76]]}
 ]},
 {club:"Granada",abbr:"GRA",color:"#A11D2A",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"2019-20",players:[["Rui Silva","GK",79],["Víctor Díaz","DEF",76],["Germán Sánchez","DEF",77],["Domingos Duarte","DEF",77],["Quini","DEF",76],["Yangel Herrera","MID",78],["Maxime Gonalons","MID",77],["Darwin Machís","MID",78],["Antonio Puertas","MID",76],["Roberto Soldado","ATT",78],["Carlos Fernández","ATT",76],["Ángel Montoro","ATT",75]]}
 ]},
 {club:"Girona",abbr:"GIR",color:"#B81E2E",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"2023-24",players:[["Paulo Gazzaniga","GK",79],["Yan Couto","DEF",78],["David López","DEF",78],["Eric García","DEF",79],["Miguel Gutiérrez","DEF",79],["Arnau Martínez","DEF",77],["Aleix García","MID",82],["Iván Martín","MID",78],["Yangel Herrera","MID",79],["Artem Dovbyk","ATT",82],["Sávio","ATT",82],["Viktor Tsygankov","ATT",81],["Portu","ATT",78]]}
 ]},
 {club:"Las Palmas",abbr:"LPA",color:"#FFD200",color2:"#1457B0",text:"#241407",seasons:[
   {season:"2023-24",players:[["Álvaro Valles","GK",78],["Sergi Cardona","DEF",76],["Saúl Coco","DEF",77],["Álex Suárez","DEF",76],["Daley Sinkgraven","DEF",76],["Kirian Rodríguez","MID",78],["Javi Muñoz","MID",76],["Enzo Loiodice","MID",76],["Alberto Moleiro","MID",78],["Sandro Ramírez","ATT",77],["Munir El Haddadi","ATT",77],["Marc Cardona","ATT",75]]}
 ]},
 {club:"Racing Santander",abbr:"RAC",color:"#2E9E4E",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"2007-08",players:[["Toño","GK",77],["Ezequiel Garay","DEF",78],["César Navas","DEF",77],["Christian Fernández","DEF",76],["Pinillos","DEF",76],["Pedro Munitis","MID",78],["Mario Regueiro","MID",77],["Gonzalo Colsa","MID",76],["Marko Smiljanić","MID",75],["Nikola Žigić","ATT",78],["Óscar Serrano","ATT",76],["Jonathan Pereira","ATT",76]]}
 ]},
 {club:"Alavés",abbr:"ALA",color:"#0761AF",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"2000-01",players:[["Martín Herrera","GK",78],["Cosmin Contra","DEF",78],["Antonio Karmona","DEF",76],["Dan Eggen","DEF",76],["Delfí Geli","DEF",77],["Ivan Tomić","MID",77],["Jordi Cruyff","MID",78],["Pablo","MID",76],["Hermes Desio","MID",76],["Javi Moreno","ATT",80],["Iván Alonso","ATT",77],["Magno","ATT",77]]}
 ]},
 {club:"Tenerife",abbr:"TEN",color:"#1457B0",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1992-93",players:[["Agustín","GK",78],["Chano","DEF",78],["César Gómez","DEF",76],["Aguado","DEF",76],["Llorente","DEF",76],["Fernando Redondo","MID",84],["Quique Estebaranz","MID",77],["Antonio Mata","MID",76],["Felipe Miñambres","MID",76],["Juan Antonio Pizzi","ATT",82],["Diego Latorre","ATT",79],["Jorge Dertycia","ATT",78]]}
 ]},
 {club:"Eibar",abbr:"EIB",color:"#9A1B30",color2:"#1457B0",text:"#fff",seasons:[
   {season:"2017-18",players:[["Marko Dmitrović","GK",78],["Paulo Oliveira","DEF",77],["Iván Ramis","DEF",76],["José Ángel","DEF",76],["Rubén Peña","DEF",77],["Dani García","MID",78],["Gonzalo Escalante","MID",77],["Joan Jordán","MID",78],["Takashi Inui","MID",78],["Rubén Pardo","MID",76],["Sergi Enrich","ATT",77],["Charles","ATT",78],["Kike García","ATT",76]]}
 ]},
 {club:"Cádiz",abbr:"CAD",color:"#F4D000",color2:"#1457B0",text:"#241407",seasons:[
   {season:"2021-22",players:[["Jeremías Ledesma","GK",77],["Iza Carcelén","DEF",76],["Fali","DEF",76],["Luis Hernández","DEF",76],["Alfonso Espino","DEF",76],["Álex Fernández","MID",77],["José Mari","MID",76],["Tomás Alarcón","MID",75],["Rubén Sobrino","MID",76],["Lucas Pérez","ATT",78],["Álvaro Negredo","ATT",78],["Choco Lozano","ATT",76]]}
 ]}
];

var OPPONENTS=[
  ["Real Madrid",89],["Barcelona",89],["Atlético Madrid",84],["Valencia",80],["Sevilla",80],
  ["Villarreal",79],["Real Sociedad",79],["Athletic Bilbao",78],["Real Betis",78],["Deportivo",78],
  ["Celta Vigo",76],["Girona",76],["Osasuna",75],["Getafe",74],["Mallorca",74],
  ["Espanyol",73],["Rayo Vallecano",73],["Las Palmas",72],["Alavés",71]
];
