/*
 * 13-0 Europa — match database
 * Real clubs/players used descriptively. Ratings & nationalities are an independent interpretation.
 * line = GK | DEF | MID | ATT ; player = [name, line, rating, nationality]
 */

var CLUBS=[
 {club:"Real Madrid",abbr:"RMA",color:"#DCC15A",color2:"#0A2148",text:"#241407",seasons:[
   {season:"1997-98",players:[["Bodo Illgner","GK",80,"GER"],["Roberto Carlos","DEF",88,"BRA"],["Fernando Hierro","DEF",85,"ESP"],["Manuel Sanchís","DEF",82,"ESP"],["Christian Panucci","DEF",80,"ITA"],["Christian Karembeu","MID",80,"FRA"],["Fernando Redondo","MID",87,"ARG"],["Clarence Seedorf","MID",84,"NED"],["Steve McManaman","MID",80,"ENG"],["Raúl","ATT",86,"ESP"],["Predrag Mijatović","ATT",84,"MNE"],["Davor Šuker","ATT",84,"CRO"],["Fernando Morientes","ATT",83,"ESP"]]},
   {season:"2001-02",players:[["Iker Casillas","GK",85,"ESP"],["Roberto Carlos","DEF",89,"BRA"],["Fernando Hierro","DEF",84,"ESP"],["Iván Helguera","DEF",82,"ESP"],["Míchel Salgado","DEF",80,"ESP"],["Zinedine Zidane","MID",94,"FRA"],["Luís Figo","MID",90,"POR"],["Claude Makélélé","MID",85,"FRA"],["Steve McManaman","MID",82,"ENG"],["Guti","MID",81,"ESP"],["Raúl","ATT",88,"ESP"],["Fernando Morientes","ATT",84,"ESP"],["Santiago Solari","ATT",80,"ARG"]]},
   {season:"2013-14",players:[["Iker Casillas","GK",85,"ESP"],["Dani Carvajal","DEF",81,"ESP"],["Sergio Ramos","DEF",88,"ESP"],["Pepe","DEF",84,"POR"],["Marcelo","DEF",85,"BRA"],["Fábio Coentrão","DEF",79,"POR"],["Luka Modrić","MID",88,"CRO"],["Xabi Alonso","MID",84,"ESP"],["Ángel Di María","MID",86,"ARG"],["Sami Khedira","MID",82,"GER"],["Isco","MID",81,"ESP"],["Cristiano Ronaldo","ATT",95,"POR"],["Karim Benzema","ATT",86,"FRA"],["Gareth Bale","ATT",88,"WAL"]]},
   {season:"2016-17",players:[["Keylor Navas","GK",84,"CRC"],["Dani Carvajal","DEF",84,"ESP"],["Sergio Ramos","DEF",89,"ESP"],["Raphaël Varane","DEF",85,"FRA"],["Marcelo","DEF",87,"BRA"],["Nacho","DEF",80,"ESP"],["Luka Modrić","MID",90,"CRO"],["Toni Kroos","MID",89,"GER"],["Casemiro","MID",85,"BRA"],["Isco","MID",85,"ESP"],["Cristiano Ronaldo","ATT",94,"POR"],["Karim Benzema","ATT",87,"FRA"],["Gareth Bale","ATT",88,"WAL"]]},
   {season:"2017-18",players:[["Keylor Navas","GK",84,"CRC"],["Dani Carvajal","DEF",84,"ESP"],["Sergio Ramos","DEF",89,"ESP"],["Raphaël Varane","DEF",85,"FRA"],["Marcelo","DEF",86,"BRA"],["Nacho","DEF",80,"ESP"],["Luka Modrić","MID",91,"CRO"],["Toni Kroos","MID",89,"GER"],["Casemiro","MID",86,"BRA"],["Isco","MID",85,"ESP"],["Marco Asensio","MID",82,"ESP"],["Cristiano Ronaldo","ATT",95,"POR"],["Karim Benzema","ATT",85,"FRA"],["Gareth Bale","ATT",86,"WAL"]]},
   {season:"2021-22",players:[["Thibaut Courtois","GK",90,"BEL"],["Dani Carvajal","DEF",83,"ESP"],["Éder Militão","DEF",84,"BRA"],["David Alaba","DEF",85,"AUT"],["Ferland Mendy","DEF",81,"FRA"],["Nacho","DEF",80,"ESP"],["Casemiro","MID",85,"BRA"],["Luka Modrić","MID",86,"CRO"],["Toni Kroos","MID",86,"GER"],["Federico Valverde","MID",83,"URU"],["Karim Benzema","ATT",92,"FRA"],["Vinícius Júnior","ATT",87,"BRA"],["Rodrygo","ATT",83,"BRA"]]}
 ]},
 {club:"Barcelona",abbr:"BAR",color:"#A50044",color2:"#004D98",text:"#fff",seasons:[
   {season:"1991-92",players:[["Andoni Zubizarreta","GK",85,"ESP"],["Nando","DEF",80,"ESP"],["Ronald Koeman","DEF",87,"NED"],["Albert Ferrer","DEF",80,"ESP"],["Juan Carlos","DEF",78,"ESP"],["José Mari Bakero","MID",83,"ESP"],["Pep Guardiola","MID",84,"ESP"],["Eusebio Sacristán","MID",81,"ESP"],["Michael Laudrup","MID",89,"DEN"],["Hristo Stoichkov","ATT",90,"BUL"],["Julio Salinas","ATT",81,"ESP"],["Txiki Begiristain","ATT",81,"ESP"]]},
   {season:"2005-06",players:[["Víctor Valdés","GK",83,"ESP"],["Juliano Belletti","DEF",80,"BRA"],["Carles Puyol","DEF",86,"ESP"],["Rafael Márquez","DEF",83,"MEX"],["Gio van Bronckhorst","DEF",80,"NED"],["Deco","MID",86,"POR"],["Xavi","MID",85,"ESP"],["Edmílson","MID",79,"BRA"],["Andrés Iniesta","MID",81,"ESP"],["Mark van Bommel","MID",79,"NED"],["Ronaldinho","ATT",93,"BRA"],["Samuel Eto'o","ATT",88,"CMR"],["Ludovic Giuly","ATT",80,"FRA"],["Henrik Larsson","ATT",82,"SWE"]]},
   {season:"2008-09",players:[["Víctor Valdés","GK",86,"ESP"],["Dani Alves","DEF",88,"BRA"],["Carles Puyol","DEF",87,"ESP"],["Gerard Piqué","DEF",85,"ESP"],["Éric Abidal","DEF",84,"FRA"],["Xavi","MID",91,"ESP"],["Andrés Iniesta","MID",90,"ESP"],["Sergio Busquets","MID",84,"ESP"],["Yaya Touré","MID",84,"CIV"],["Seydou Keita","MID",80,"MLI"],["Lionel Messi","ATT",93,"ARG"],["Samuel Eto'o","ATT",89,"CMR"],["Thierry Henry","ATT",86,"FRA"]]},
   {season:"2010-11",players:[["Víctor Valdés","GK",86,"ESP"],["Dani Alves","DEF",88,"BRA"],["Gerard Piqué","DEF",87,"ESP"],["Carles Puyol","DEF",86,"ESP"],["Éric Abidal","DEF",83,"FRA"],["Xavi","MID",92,"ESP"],["Andrés Iniesta","MID",91,"ESP"],["Sergio Busquets","MID",85,"ESP"],["Javier Mascherano","MID",84,"ARG"],["Seydou Keita","MID",80,"MLI"],["Lionel Messi","ATT",94,"ARG"],["David Villa","ATT",89,"ESP"],["Pedro","ATT",83,"ESP"]]},
   {season:"2014-15",players:[["Marc-André ter Stegen","GK",84,"GER"],["Dani Alves","DEF",86,"BRA"],["Gerard Piqué","DEF",87,"ESP"],["Javier Mascherano","DEF",85,"ARG"],["Jordi Alba","DEF",86,"ESP"],["Sergio Busquets","MID",87,"ESP"],["Andrés Iniesta","MID",89,"ESP"],["Ivan Rakitić","MID",85,"CRO"],["Xavi","MID",86,"ESP"],["Lionel Messi","ATT",95,"ARG"],["Luis Suárez","ATT",91,"URU"],["Neymar","ATT",90,"BRA"],["Pedro","ATT",81,"ESP"]]}
 ]},
 {club:"Bayern Munich",abbr:"BAY",color:"#DC052D",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1975-76",players:[["Sepp Maier","GK",85,"GER"],["Franz Beckenbauer","DEF",90,"GER"],["Hans-Georg Schwarzenbeck","DEF",80,"GER"],["Björn Andersson","DEF",78,"SWE"],["Johnny Hansen","DEF",78,"DEN"],["Franz Roth","MID",80,"GER"],["Bernd Dürnberger","MID",78,"GER"],["Jupp Kapellmann","MID",79,"GER"],["Uli Hoeneß","ATT",84,"GER"],["Gerd Müller","ATT",90,"GER"],["Karl-Heinz Rummenigge","ATT",85,"GER"]]},
   {season:"2000-01",players:[["Oliver Kahn","GK",88,"GER"],["Willy Sagnol","DEF",81,"FRA"],["Thomas Linke","DEF",79,"GER"],["Samuel Kuffour","DEF",80,"GHA"],["Bixente Lizarazu","DEF",83,"FRA"],["Stefan Effenberg","MID",84,"GER"],["Owen Hargreaves","MID",80,"ENG"],["Mehmet Scholl","MID",83,"GER"],["Hasan Salihamidžić","MID",80,"BIH"],["Giovane Élber","ATT",83,"BRA"],["Carsten Jancker","ATT",80,"GER"],["Paulo Sérgio","ATT",80,"BRA"]]},
   {season:"2012-13",players:[["Manuel Neuer","GK",89,"GER"],["Philipp Lahm","DEF",87,"GER"],["Jérôme Boateng","DEF",83,"GER"],["Dante","DEF",82,"BRA"],["David Alaba","DEF",84,"AUT"],["Bastian Schweinsteiger","MID",87,"GER"],["Javi Martínez","MID",84,"ESP"],["Toni Kroos","MID",85,"GER"],["Arjen Robben","ATT",88,"NED"],["Franck Ribéry","ATT",89,"FRA"],["Thomas Müller","ATT",86,"GER"],["Mario Mandžukić","ATT",83,"CRO"]]},
   {season:"2019-20",players:[["Manuel Neuer","GK",89,"GER"],["Joshua Kimmich","DEF",87,"GER"],["Jérôme Boateng","DEF",82,"GER"],["David Alaba","DEF",85,"AUT"],["Alphonso Davies","DEF",83,"CAN"],["Leon Goretzka","MID",84,"GER"],["Thiago","MID",86,"ESP"],["Thomas Müller","MID",86,"GER"],["Serge Gnabry","ATT",85,"GER"],["Kingsley Coman","ATT",83,"FRA"],["Robert Lewandowski","ATT",92,"POL"]]}
 ]},
 {club:"AC Milan",abbr:"MIL",color:"#FB090B",color2:"#000000",text:"#fff",seasons:[
   {season:"1989-90",players:[["Giovanni Galli","GK",81,"ITA"],["Mauro Tassotti","DEF",81,"ITA"],["Franco Baresi","DEF",90,"ITA"],["Alessandro Costacurta","DEF",84,"ITA"],["Paolo Maldini","DEF",89,"ITA"],["Frank Rijkaard","MID",88,"NED"],["Carlo Ancelotti","MID",82,"ITA"],["Roberto Donadoni","MID",83,"ITA"],["Angelo Colombo","MID",78,"ITA"],["Ruud Gullit","ATT",91,"NED"],["Marco van Basten","ATT",92,"NED"]]},
   {season:"1993-94",players:[["Sebastiano Rossi","GK",82,"ITA"],["Mauro Tassotti","DEF",81,"ITA"],["Franco Baresi","DEF",89,"ITA"],["Paolo Maldini","DEF",89,"ITA"],["Christian Panucci","DEF",80,"ITA"],["Marcel Desailly","MID",85,"FRA"],["Demetrio Albertini","MID",83,"ITA"],["Roberto Donadoni","MID",83,"ITA"],["Zvonimir Boban","MID",84,"CRO"],["Daniele Massaro","ATT",80,"ITA"],["Dejan Savićević","ATT",85,"MNE"],["Brian Laudrup","ATT",84,"DEN"]]},
   {season:"2002-03",players:[["Dida","GK",83,"BRA"],["Alessandro Costacurta","DEF",80,"ITA"],["Alessandro Nesta","DEF",88,"ITA"],["Paolo Maldini","DEF",86,"ITA"],["Kakha Kaladze","DEF",80,"GEO"],["Gennaro Gattuso","MID",83,"ITA"],["Andrea Pirlo","MID",87,"ITA"],["Clarence Seedorf","MID",85,"NED"],["Manuel Rui Costa","MID",84,"POR"],["Andriy Shevchenko","ATT",90,"UKR"],["Filippo Inzaghi","ATT",84,"ITA"]]},
   {season:"2006-07",players:[["Dida","GK",82,"BRA"],["Massimo Oddo","DEF",79,"ITA"],["Alessandro Nesta","DEF",87,"ITA"],["Paolo Maldini","DEF",84,"ITA"],["Marek Jankulovski","DEF",79,"CZE"],["Gennaro Gattuso","MID",83,"ITA"],["Andrea Pirlo","MID",88,"ITA"],["Massimo Ambrosini","MID",80,"ITA"],["Clarence Seedorf","MID",84,"NED"],["Kaká","ATT",92,"BRA"],["Filippo Inzaghi","ATT",84,"ITA"]]}
 ]},
 {club:"Liverpool",abbr:"LIV",color:"#C8102E",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1983-84",players:[["Bruce Grobbelaar","GK",81,"ZIM"],["Phil Neal","DEF",80,"ENG"],["Mark Lawrenson","DEF",82,"IRL"],["Alan Hansen","DEF",84,"SCO"],["Alan Kennedy","DEF",79,"ENG"],["Graeme Souness","MID",86,"SCO"],["Sammy Lee","MID",79,"ENG"],["Ronnie Whelan","MID",80,"IRL"],["Craig Johnston","MID",79,"AUS"],["Kenny Dalglish","ATT",88,"SCO"],["Ian Rush","ATT",86,"WAL"]]},
   {season:"2004-05",players:[["Jerzy Dudek","GK",80,"POL"],["Steve Finnan","DEF",79,"IRL"],["Jamie Carragher","DEF",83,"ENG"],["Sami Hyypiä","DEF",83,"FIN"],["Djimi Traoré","DEF",76,"MLI"],["Steven Gerrard","MID",89,"ENG"],["Xabi Alonso","MID",85,"ESP"],["Dietmar Hamann","MID",81,"GER"],["Luis García","MID",80,"ESP"],["John Arne Riise","MID",80,"NOR"],["Milan Baroš","ATT",80,"CZE"],["Harry Kewell","ATT",80,"AUS"]]},
   {season:"2018-19",players:[["Alisson","GK",88,"BRA"],["Trent Alexander-Arnold","DEF",84,"ENG"],["Virgil van Dijk","DEF",90,"NED"],["Joël Matip","DEF",81,"CMR"],["Andy Robertson","DEF",85,"SCO"],["Fabinho","MID",84,"BRA"],["Jordan Henderson","MID",82,"ENG"],["Georginio Wijnaldum","MID",83,"NED"],["James Milner","MID",80,"ENG"],["Mohamed Salah","ATT",90,"EGY"],["Sadio Mané","ATT",89,"SEN"],["Roberto Firmino","ATT",86,"BRA"]]}
 ]},
 {club:"Manchester United",abbr:"MUN",color:"#DA291C",color2:"#FBE122",text:"#fff",seasons:[
   {season:"1967-68",players:[["Alex Stepney","GK",80,"ENG"],["Shay Brennan","DEF",78,"IRL"],["Bill Foulkes","DEF",79,"ENG"],["Tony Dunne","DEF",79,"IRL"],["Nobby Stiles","MID",81,"ENG"],["Pat Crerand","MID",81,"SCO"],["Bobby Charlton","MID",90,"ENG"],["George Best","ATT",92,"NIR"],["Denis Law","ATT",88,"SCO"],["Brian Kidd","ATT",80,"ENG"],["David Sadler","ATT",78,"ENG"]]},
   {season:"1998-99",players:[["Peter Schmeichel","GK",87,"DEN"],["Gary Neville","DEF",81,"ENG"],["Jaap Stam","DEF",85,"NED"],["Ronny Johnsen","DEF",80,"NOR"],["Denis Irwin","DEF",81,"IRL"],["David Beckham","MID",87,"ENG"],["Roy Keane","MID",88,"IRL"],["Paul Scholes","MID",86,"ENG"],["Ryan Giggs","MID",86,"WAL"],["Dwight Yorke","ATT",85,"TRI"],["Andy Cole","ATT",83,"ENG"],["Teddy Sheringham","ATT",82,"ENG"]]},
   {season:"2007-08",players:[["Edwin van der Sar","GK",85,"NED"],["Wes Brown","DEF",80,"ENG"],["Rio Ferdinand","DEF",87,"ENG"],["Nemanja Vidić","DEF",87,"SRB"],["Patrice Evra","DEF",84,"FRA"],["Michael Carrick","MID",83,"ENG"],["Paul Scholes","MID",85,"ENG"],["Owen Hargreaves","MID",81,"ENG"],["Ryan Giggs","MID",84,"WAL"],["Cristiano Ronaldo","ATT",92,"POR"],["Wayne Rooney","ATT",87,"ENG"],["Carlos Tévez","ATT",85,"ARG"]]}
 ]},
 {club:"Inter Milan",abbr:"INT",color:"#1E50A0",color2:"#000000",text:"#fff",seasons:[
   {season:"1964-65",players:[["Giuliano Sarti","GK",82,"ITA"],["Tarcisio Burgnich","DEF",83,"ITA"],["Aristide Guarneri","DEF",80,"ITA"],["Armando Picchi","DEF",82,"ITA"],["Giacinto Facchetti","DEF",87,"ITA"],["Carlo Tagnin","MID",78,"ITA"],["Luis Suárez","MID",88,"URU"],["Gianfranco Bedin","MID",78,"ITA"],["Jair","ATT",83,"BRA"],["Sandro Mazzola","ATT",87,"ITA"],["Mario Corso","ATT",84,"ITA"]]},
   {season:"2009-10",players:[["Júlio César","GK",86,"BRA"],["Maicon","DEF",85,"BRA"],["Lúcio","DEF",84,"BRA"],["Walter Samuel","DEF",83,"ARG"],["Cristian Chivu","DEF",80,"ROU"],["Javier Zanetti","MID",85,"ARG"],["Esteban Cambiasso","MID",84,"ARG"],["Wesley Sneijder","MID",87,"NED"],["Goran Pandev","MID",80,"MKD"],["Samuel Eto'o","ATT",88,"CMR"],["Diego Milito","ATT",86,"ARG"]]},
   {season:"2022-23",players:[["André Onana","GK",83,"CMR"],["Matteo Darmian","DEF",78,"ITA"],["Francesco Acerbi","DEF",80,"ITA"],["Alessandro Bastoni","DEF",84,"ITA"],["Federico Dimarco","DEF",81,"ITA"],["Nicolò Barella","MID",85,"ITA"],["Marcelo Brozović","MID",82,"CRO"],["Hakan Çalhanoğlu","MID",83,"TUR"],["Denzel Dumfries","MID",80,"NED"],["Lautaro Martínez","ATT",86,"ARG"],["Edin Džeko","ATT",81,"BIH"],["Romelu Lukaku","ATT",83,"BEL"]]}
 ]},
 {club:"Juventus",abbr:"JUV",color:"#111111",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1984-85",players:[["Stefano Tacconi","GK",81,"ITA"],["Claudio Gentile","DEF",82,"ITA"],["Gaetano Scirea","DEF",87,"ITA"],["Sergio Brio","DEF",80,"ITA"],["Antonio Cabrini","DEF",83,"ITA"],["Massimo Bonini","MID",80,"SMR"],["Marco Tardelli","MID",84,"ITA"],["Michel Platini","MID",92,"FRA"],["Zbigniew Boniek","MID",84,"POL"],["Paolo Rossi","ATT",86,"ITA"],["Massimo Briaschi","ATT",78,"ITA"]]},
   {season:"1995-96",players:[["Angelo Peruzzi","GK",85,"ITA"],["Ciro Ferrara","DEF",83,"ITA"],["Paolo Montero","DEF",82,"URU"],["Pietro Vierchowod","DEF",82,"ITA"],["Gianluca Pessotto","DEF",79,"ITA"],["Didier Deschamps","MID",83,"FRA"],["Antonio Conte","MID",81,"ITA"],["Paulo Sousa","MID",82,"POR"],["Angelo Di Livio","MID",78,"ITA"],["Alessandro Del Piero","ATT",88,"ITA"],["Gianluca Vialli","ATT",85,"ITA"],["Fabrizio Ravanelli","ATT",83,"ITA"]]},
   {season:"2014-15",players:[["Gianluigi Buffon","GK",88,"ITA"],["Stephan Lichtsteiner","DEF",80,"SUI"],["Andrea Barzagli","DEF",84,"ITA"],["Leonardo Bonucci","DEF",85,"ITA"],["Giorgio Chiellini","DEF",86,"ITA"],["Patrice Evra","DEF",80,"FRA"],["Paul Pogba","MID",87,"FRA"],["Arturo Vidal","MID",85,"CHI"],["Claudio Marchisio","MID",83,"ITA"],["Andrea Pirlo","MID",85,"ITA"],["Carlos Tévez","ATT",86,"ARG"],["Álvaro Morata","ATT",81,"ESP"]]}
 ]},
 {club:"Ajax",abbr:"AJA",color:"#D2122E",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1972-73",players:[["Heinz Stuy","GK",80,"NED"],["Wim Suurbier","DEF",81,"NED"],["Horst Blankenburg","DEF",80,"GER"],["Barry Hulshoff","DEF",80,"NED"],["Ruud Krol","DEF",85,"NED"],["Johan Neeskens","MID",87,"NED"],["Arie Haan","MID",82,"NED"],["Gerrie Mühren","MID",81,"NED"],["Johnny Rep","ATT",84,"NED"],["Johan Cruyff","ATT",93,"NED"],["Piet Keizer","ATT",83,"NED"]]},
   {season:"1994-95",players:[["Edwin van der Sar","GK",84,"NED"],["Michael Reiziger","DEF",80,"NED"],["Danny Blind","DEF",82,"NED"],["Frank de Boer","DEF",83,"NED"],["Frank Rijkaard","DEF",85,"NED"],["Clarence Seedorf","MID",84,"NED"],["Edgar Davids","MID",84,"NED"],["Jari Litmanen","MID",86,"FIN"],["Ronald de Boer","MID",82,"NED"],["Marc Overmars","ATT",85,"NED"],["Patrick Kluivert","ATT",84,"NED"],["Finidi George","ATT",81,"NGA"]]}
 ]},
 {club:"Borussia Dortmund",abbr:"BVB",color:"#FDE100",color2:"#000000",text:"#241407",seasons:[
   {season:"1996-97",players:[["Stefan Klos","GK",80,"GER"],["Jürgen Kohler","DEF",84,"GER"],["Matthias Sammer","DEF",87,"GER"],["Stefan Reuter","DEF",80,"GER"],["Jörg Heinrich","DEF",80,"GER"],["Paul Lambert","MID",79,"SCO"],["Andreas Möller","MID",84,"GER"],["Paulo Sousa","MID",81,"POR"],["Lars Ricken","ATT",80,"GER"],["Karl-Heinz Riedle","ATT",82,"GER"],["Stéphane Chapuisat","ATT",84,"SUI"]]},
   {season:"2012-13",players:[["Roman Weidenfeller","GK",82,"GER"],["Łukasz Piszczek","DEF",82,"POL"],["Mats Hummels","DEF",86,"GER"],["Neven Subotić","DEF",81,"SRB"],["Marcel Schmelzer","DEF",80,"GER"],["İlkay Gündoğan","MID",84,"GER"],["Sven Bender","MID",80,"GER"],["Mario Götze","MID",85,"GER"],["Marco Reus","ATT",86,"GER"],["Jakub Błaszczykowski","ATT",81,"POL"],["Robert Lewandowski","ATT",87,"POL"]]},
   {season:"2023-24",players:[["Gregor Kobel","GK",84,"SUI"],["Julian Ryerson","DEF",78,"NOR"],["Mats Hummels","DEF",82,"GER"],["Nico Schlotterbeck","DEF",81,"GER"],["Ian Maatsen","DEF",79,"NED"],["Emre Can","MID",80,"GER"],["Marcel Sabitzer","MID",81,"AUT"],["Julian Brandt","MID",83,"GER"],["Jadon Sancho","ATT",81,"ENG"],["Karim Adeyemi","ATT",80,"GER"],["Niclas Füllkrug","ATT",80,"GER"]]}
 ]},
 {club:"Chelsea",abbr:"CHE",color:"#034694",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"2011-12",players:[["Petr Čech","GK",86,"CZE"],["Branislav Ivanović","DEF",83,"SRB"],["John Terry","DEF",85,"ENG"],["David Luiz","DEF",82,"BRA"],["Ashley Cole","DEF",85,"ENG"],["John Obi Mikel","MID",80,"NGA"],["Frank Lampard","MID",86,"ENG"],["Ramires","MID",82,"BRA"],["Juan Mata","MID",84,"ESP"],["Didier Drogba","ATT",87,"CIV"],["Daniel Sturridge","ATT",80,"ENG"]]},
   {season:"2020-21",players:[["Édouard Mendy","GK",83,"SEN"],["Reece James","DEF",81,"ENG"],["Andreas Christensen","DEF",80,"DEN"],["Thiago Silva","DEF",85,"BRA"],["Antonio Rüdiger","DEF",83,"GER"],["Ben Chilwell","DEF",81,"ENG"],["N'Golo Kanté","MID",88,"FRA"],["Jorginho","MID",84,"ITA"],["Mason Mount","MID",83,"ENG"],["Kai Havertz","ATT",83,"GER"],["Timo Werner","ATT",81,"GER"]]}
 ]},
 {club:"Manchester City",abbr:"MCI",color:"#6CABDD",color2:"#1C2C5B",text:"#06203f",seasons:[
   {season:"2022-23",players:[["Ederson","GK",88,"BRA"],["Kyle Walker","DEF",84,"ENG"],["John Stones","DEF",84,"ENG"],["Manuel Akanji","DEF",83,"SUI"],["Nathan Aké","DEF",82,"NED"],["Rúben Dias","DEF",87,"POR"],["Rodri","MID",89,"ESP"],["Kevin De Bruyne","MID",91,"BEL"],["İlkay Gündoğan","MID",85,"GER"],["Bernardo Silva","MID",86,"POR"],["Jack Grealish","ATT",84,"ENG"],["Erling Haaland","ATT",91,"NOR"]]}
 ]},
 {club:"Porto",abbr:"POR",color:"#0046AB",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1986-87",players:[["Józef Mlynarczyk","GK",80,"POL"],["João Pinto","DEF",80,"POR"],["Celso","DEF",78,"POR"],["Eduardo Luís","DEF",78,"POR"],["Quim","MID",78,"POR"],["Jaime Magalhães","MID",78,"POR"],["António André","MID",79,"POR"],["Jaime Pacheco","MID",78,"POR"],["Paulo Futre","ATT",87,"POR"],["Rabah Madjer","ATT",83,"ALG"],["Juary","ATT",80,"BRA"]]},
   {season:"2003-04",players:[["Vítor Baía","GK",83,"POR"],["Paulo Ferreira","DEF",80,"POR"],["Jorge Costa","DEF",80,"POR"],["Ricardo Carvalho","DEF",84,"POR"],["Nuno Valente","DEF",78,"POR"],["Costinha","MID",81,"POR"],["Maniche","MID",82,"POR"],["Deco","MID",87,"POR"],["Pedro Mendes","MID",79,"POR"],["Derlei","ATT",80,"BRA"],["Benni McCarthy","ATT",80,"RSA"],["Dmitri Alenichev","ATT",80,"RUS"]]}
 ]},
 {club:"Paris Saint-Germain",abbr:"PSG",color:"#004170",color2:"#DA291C",text:"#fff",seasons:[
   {season:"2019-20",players:[["Keylor Navas","GK",85,"CRC"],["Thilo Kehrer","DEF",79,"GER"],["Thiago Silva","DEF",85,"BRA"],["Presnel Kimpembe","DEF",81,"FRA"],["Juan Bernat","DEF",80,"ESP"],["Marquinhos","MID",85,"BRA"],["Marco Verratti","MID",86,"ITA"],["Ander Herrera","MID",81,"ESP"],["Ángel Di María","MID",85,"ARG"],["Kylian Mbappé","ATT",91,"FRA"],["Neymar","ATT",91,"BRA"],["Mauro Icardi","ATT",83,"ARG"]]}
 ]},
 {club:"Atlético Madrid",abbr:"ATM",color:"#C8102E",color2:"#1A2A6C",text:"#fff",seasons:[
   {season:"2013-14",players:[["Thibaut Courtois","GK",87,"BEL"],["Juanfran","DEF",82,"ESP"],["Diego Godín","DEF",87,"URU"],["Miranda","DEF",84,"BRA"],["Filipe Luís","DEF",84,"BRA"],["Gabi","MID",81,"ESP"],["Tiago","MID",80,"POR"],["Koke","MID",84,"ESP"],["Arda Turan","MID",84,"TUR"],["Diego Costa","ATT",88,"ESP"],["David Villa","ATT",83,"ESP"]]},
   {season:"2015-16",players:[["Jan Oblak","GK",86,"SVN"],["Juanfran","DEF",81,"ESP"],["Diego Godín","DEF",87,"URU"],["José Giménez","DEF",81,"URU"],["Filipe Luís","DEF",83,"BRA"],["Gabi","MID",81,"ESP"],["Koke","MID",84,"ESP"],["Saúl","MID",81,"ESP"],["Yannick Carrasco","MID",81,"BEL"],["Antoine Griezmann","ATT",88,"FRA"],["Fernando Torres","ATT",81,"ESP"]]}
 ]},
 {club:"Marseille",abbr:"OM",color:"#2FAEE0",color2:"#FFFFFF",text:"#06283a",seasons:[
   {season:"1992-93",players:[["Fabien Barthez","GK",83,"FRA"],["Jocelyn Angloma","DEF",80,"FRA"],["Basile Boli","DEF",82,"FRA"],["Marcel Desailly","DEF",84,"FRA"],["Eric Di Meco","DEF",78,"FRA"],["Didier Deschamps","MID",83,"FRA"],["Franck Sauzée","MID",82,"FRA"],["Jean-Jacques Eydelie","MID",78,"FRA"],["Abedi Pelé","MID",87,"GHA"],["Alen Bokšić","ATT",83,"CRO"],["Rudi Völler","ATT",85,"GER"]]}
 ]},
 {club:"Nottingham Forest",abbr:"NFO",color:"#DD0000",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1979-80",players:[["Peter Shilton","GK",86,"ENG"],["Viv Anderson","DEF",80,"ENG"],["Larry Lloyd","DEF",80,"ENG"],["Kenny Burns","DEF",81,"SCO"],["Frank Gray","DEF",78,"SCO"],["John McGovern","MID",79,"SCO"],["Ian Bowyer","MID",78,"ENG"],["Archie Gemmill","MID",81,"SCO"],["John Robertson","ATT",83,"SCO"],["Trevor Francis","ATT",84,"ENG"],["Garry Birtles","ATT",80,"ENG"]]}
 ]},
 {club:"Benfica",abbr:"BEN",color:"#E40521",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1961-62",players:[["Costa Pereira","GK",81,"POR"],["Mário João","DEF",78,"POR"],["Germano","DEF",82,"POR"],["Ângelo Martins","DEF",78,"POR"],["Fernando Cruz","DEF",78,"POR"],["Mário Coluna","MID",86,"POR"],["Domiciano Cavém","MID",79,"POR"],["José Augusto","MID",82,"POR"],["José Águas","ATT",83,"POR"],["Eusébio","ATT",91,"POR"],["António Simões","ATT",81,"POR"]]}
 ]},
 {club:"Celtic",abbr:"CEL",color:"#18914F",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1966-67",players:[["Ronnie Simpson","GK",80,"SCO"],["Jim Craig","DEF",78,"SCO"],["Billy McNeill","DEF",83,"SCO"],["John Clark","DEF",78,"SCO"],["Tommy Gemmell","DEF",81,"SCO"],["Bobby Murdoch","MID",83,"SCO"],["Bertie Auld","MID",81,"SCO"],["Jimmy Johnstone","ATT",85,"SCO"],["Willie Wallace","ATT",80,"SCO"],["Stevie Chalmers","ATT",80,"SCO"],["Bobby Lennox","ATT",81,"SCO"]]}
 ]},
 {club:"Hamburg",abbr:"HSV",color:"#0A3A82",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1982-83",players:[["Uli Stein","GK",81,"GER"],["Manfred Kaltz","DEF",83,"GER"],["Holger Hieronymus","DEF",79,"GER"],["Ditmar Jakobs","DEF",79,"GER"],["Jürgen Groh","DEF",78,"GER"],["Felix Magath","MID",84,"GER"],["Wolfgang Rolff","MID",79,"GER"],["Jürgen Milewski","MID",79,"GER"],["Lars Bastrup","ATT",80,"DEN"],["Horst Hrubesch","ATT",84,"GER"],["Thomas von Heesen","ATT",80,"GER"]]}
 ]},
 {club:"PSV Eindhoven",abbr:"PSV",color:"#ED1C24",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"1987-88",players:[["Hans van Breukelen","GK",83,"NED"],["Eric Gerets","DEF",82,"BEL"],["Ronald Koeman","DEF",87,"NED"],["Berry van Aerle","DEF",79,"NED"],["Søren Lerby","MID",82,"DEN"],["Gerald Vanenburg","MID",82,"NED"],["Jan Heintze","DEF",79,"DEN"],["Edward Linskens","MID",78,"NED"],["Hans Gillhaus","ATT",80,"NED"],["Wim Kieft","ATT",83,"NED"],["René Eijkelkamp","ATT",78,"NED"]]}
 ]},
 {club:"Red Star Belgrade",abbr:"RSB",color:"#ED1C24",color2:"#0033A0",text:"#fff",seasons:[
   {season:"1990-91",players:[["Stevan Stojanović","GK",81,"SRB"],["Duško Radinović","DEF",78,"SRB"],["Miodrag Belodedici","DEF",82,"ROU"],["Slobodan Marović","DEF",78,"SRB"],["Refik Šabanadžović","DEF",78,"BIH"],["Vladimir Jugović","MID",82,"SRB"],["Siniša Mihajlović","MID",84,"SRB"],["Robert Prosinečki","MID",86,"CRO"],["Dejan Savićević","ATT",86,"MNE"],["Darko Pančev","ATT",85,"MKD"],["Vladan Lukić","ATT",79,"SRB"]]}
 ]},
 {club:"Feyenoord",abbr:"FEY",color:"#C8102E",color2:"#000000",text:"#fff",seasons:[
   {season:"1969-70",players:[["Eddy Pieters Graafland","GK",80,"NED"],["Piet Romeijn","DEF",78,"NED"],["Rinus Israël","DEF",82,"NED"],["Theo Laseroms","DEF",79,"NED"],["Theo van Duivenbode","DEF",78,"NED"],["Franz Hasil","MID",82,"AUT"],["Wim Jansen","MID",83,"NED"],["Wim van Hanegem","MID",85,"NED"],["Henk Wery","ATT",80,"NED"],["Ove Kindvall","ATT",83,"SWE"],["Coen Moulijn","ATT",83,"NED"]]}
 ]},
 {club:"Bayer Leverkusen",abbr:"LEV",color:"#E32219",color2:"#000000",text:"#fff",seasons:[
   {season:"2001-02",players:[["Hans-Jörg Butt","GK",80,"GER"],["Diego Placente","DEF",78,"ARG"],["Jens Nowotny","DEF",82,"GER"],["Lúcio","DEF",83,"BRA"],["Zé Roberto","DEF",83,"BRA"],["Michael Ballack","MID",88,"GER"],["Carsten Ramelow","MID",80,"GER"],["Bernd Schneider","MID",82,"GER"],["Yıldıray Baştürk","MID",80,"TUR"],["Oliver Neuville","ATT",81,"GER"],["Dimitar Berbatov","ATT",83,"BUL"]]}
 ]},
 {club:"Tottenham Hotspur",abbr:"TOT",color:"#1C2C5B",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"2018-19",players:[["Hugo Lloris","GK",84,"FRA"],["Kieran Trippier","DEF",81,"ENG"],["Toby Alderweireld","DEF",84,"BEL"],["Jan Vertonghen","DEF",84,"BEL"],["Danny Rose","DEF",80,"ENG"],["Moussa Sissoko","MID",80,"FRA"],["Harry Winks","MID",78,"ENG"],["Christian Eriksen","MID",86,"DEN"],["Dele Alli","MID",82,"ENG"],["Son Heung-min","ATT",86,"KOR"],["Harry Kane","ATT",88,"ENG"],["Lucas Moura","ATT",81,"BRA"]]}
 ]},
 {club:"Valencia",abbr:"VAL",color:"#F18E00",color2:"#000000",text:"#241407",seasons:[
   {season:"2000-01",players:[["Santiago Cañizares","GK",84,"ESP"],["Jocelyn Angloma","DEF",80,"FRA"],["Roberto Ayala","DEF",85,"ARG"],["Mauricio Pellegrino","DEF",79,"ARG"],["Amedeo Carboni","DEF",78,"ITA"],["Gaizka Mendieta","MID",86,"ESP"],["Rubén Baraja","MID",82,"ESP"],["David Albelda","MID",81,"ESP"],["Kily González","MID",80,"ARG"],["Pablo Aimar","ATT",85,"ARG"],["John Carew","ATT",80,"NOR"],["Juan Sánchez","ATT",79,"ESP"]]}
 ]},
 {club:"Monaco",abbr:"MON",color:"#E51B22",color2:"#FFFFFF",text:"#fff",seasons:[
   {season:"2003-04",players:[["Flavio Roma","GK",80,"ITA"],["Hugo Ibarra","DEF",78,"ARG"],["Sébastien Squillaci","DEF",80,"FRA"],["Gaël Givet","DEF",80,"FRA"],["Patrice Evra","DEF",82,"FRA"],["Lucas Bernardi","MID",80,"ARG"],["Akis Zikos","MID",78,"GRE"],["Jérôme Rothen","MID",82,"FRA"],["Ludovic Giuly","ATT",84,"FRA"],["Fernando Morientes","ATT",84,"ESP"],["Dado Pršo","ATT",81,"CRO"]]}
 ]}
];

var OPPONENTS=[
  ["Real Madrid",89],["Barcelona",88],["Bayern Munich",88],["Manchester City",87],["Liverpool",85],["AC Milan",84],["Manchester United",84],["Inter Milan",83],["Juventus",83],["Paris Saint-Germain",83],["Chelsea",82],["Atlético Madrid",82],["Borussia Dortmund",80],["Ajax",80],["Arsenal",80],["Napoli",80],["Benfica",78],["Porto",78],["Tottenham Hotspur",78]
];
